// generated from rosidl_generator_cpp/resource/idl__experimental_traits.hpp.em
// with input from @(package_name):@(interface_path)
// generated code does not contain a copyright notice
@{from rosidl_pycommon import convert_camel_case_to_lower_case_underscore}
// IWYU pragma: private, include "@(package_name)/experimental/@(convert_camel_case_to_lower_case_underscore(interface_path.stem)).hpp"

@
@#######################################################################
@# EmPy template for generating <idl>__experimental_traits.hpp files
@#
@# Context:
@#  - package_name (string)
@#  - interface_path (Path relative to the directory named after the package)
@#  - content (IdlContent, list of elements, e.g. Messages or Services)
@#######################################################################
@{
from rosidl_pycommon import convert_camel_case_to_lower_case_underscore
include_parts = [package_name] + list(interface_path.parents[0].parts) + [
    'detail', convert_camel_case_to_lower_case_underscore(interface_path.stem)]
include_base = '/'.join(include_parts)
header_guard_variable = '__'.join([x.upper() for x in include_parts]) + \
    '__EXPERIMENTAL_TRAITS_HPP_'

include_directives = set()
}@

#ifndef @(header_guard_variable)
#define @(header_guard_variable)

#include <stdint.h>

#include <array>
#include <cstddef>
#include <ostream>
#include <sstream>
#include <string>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <utility>

#include "@(include_base)__experimental_struct.hpp"
#include "rosidl_runtime_cpp/traits.hpp"

// value_to_yaml overloads for experimental string types, generated by rosidl_generator_cpp.
// Covers rosidl_runtime_cpp::{,Bounded}{,W}String as instances of BasicString<CharT, N>.
namespace rosidl_generator_traits
{

template<typename CharT, std::size_t UpperBound>
inline void value_to_yaml(
  const rosidl_runtime_cpp::BasicString<CharT, UpperBound> & s,
  std::ostream & out)
{
  value_to_yaml(std::basic_string<CharT>(s.begin(), s.end()), out);
}

}  // namespace rosidl_generator_traits

@#######################################################################
@# Handle message
@#######################################################################
@{
from rosidl_parser.definition import Message
}@
@[for message in content.get_elements_of_type(Message)]@
@{
TEMPLATE(
    'msg__experimental_traits.hpp.em',
    package_name=package_name, interface_path=interface_path, message=message,
    include_directives=include_directives)
}@

@[end for]@
@#######################################################################
@# Handle service
@#######################################################################
@{
from rosidl_parser.definition import Service
}@
@[for service in content.get_elements_of_type(Service)]@
@{
TEMPLATE(
    'srv__experimental_traits.hpp.em',
    package_name=package_name, interface_path=interface_path, service=service,
    include_directives=include_directives)
}@

@[end for]@
@#######################################################################
@# Handle action
@#######################################################################
@{
from rosidl_parser.definition import Action
}@
@[for action in content.get_elements_of_type(Action)]@
@{
TEMPLATE(
    'action__experimental_traits.hpp.em',
    package_name=package_name, interface_path=interface_path,
    action=action, include_directives=include_directives)
}@

@[end for]@
#endif  // @(header_guard_variable)
